version : '3.7'

services:
    app:
        build:
            context: ./server
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                OVERCOOKED_BRANCH: "${OVERCOOKED_BRANCH:-master}"
                GRAPHICS: "${GRAPHICS:-overcooked_graphics_v2.2.js}"
                GITHUB_TOKEN: "${GITHUB_TOKEN}"
                REPO_URL: "${REPO_URL}"
            shm_size: "5gb"
        shm_size: "5gb"
        stdin_open: true        # Moved outside 'build'
        tty: true           
        environment: 
            FLASK_ENV: "${BUILD_ENV:-production}"
        ports:
            - "80:5000"
        volumes:
            - data:/app/data
        env_file:
        - .env            
volumes:
  data:
        
